import type { Config } from "tailwindcss";

// Design tokens ported from the Stitch "Sarah Jenkins Realty" mockups
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f4",
        "on-background": "#1c1c19",
        surface: "#fcf9f4",
        "on-surface": "#1c1c19",
        "surface-variant": "#e5e2dd",
        "on-surface-variant": "#414944",
        "surface-container": "#f0ede8",
        "surface-container-low": "#f6f3ee",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e5e2dd",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcdad5",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f3f0eb",
        primary: "#00261b",
        "on-primary": "#ffffff",
        "primary-container": "#0b3d2e",
        "on-primary-container": "#79a894",
        "primary-fixed": "#bcedd7",
        "primary-fixed-dim": "#a0d1bc",
        secondary: "#12629d",
        "on-secondary": "#ffffff",
        "secondary-container": "#80bdfe",
        "on-secondary-container": "#004c7e",
        tertiary: "#2e1d00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#46320c",
        "on-tertiary-container": "#b89a6b",
        outline: "#717974",
        "outline-variant": "#c0c8c3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      spacing: {
        gutter: "16px",
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "64px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
